[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts"
]

[start]
cmd = "php artisan queue:work --tries=3 --timeout=90 --sleep=3"

